-- ALTER TABLE users ADD COLUMN is_active BOOLEAN DEFAULT TRUE;
-- SELECT * FROM users;
-- ALTER TABLE users DROP COLUMN is_active;
-- ALTER TABLE users MODIFY COLUMN name VARCHAR(150);
ALTER TABLE users MODIFY COLUMN email VARCHAR(100) FIRST;
-- SELECT * FROM users
ALTER TABLE users MODIFY COLUMN gender 
ENUM('Male', 'Female', 'Other') AFTER name;